# Generated by Django 3.1.14 on 2022-04-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='название англ.')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='название яп.')),
                ('photo', models.ImageField(null=True, upload_to='images', verbose_name='фото')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='предыдущая эволюция')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(default=None, verbose_name='появляется')),
                ('disappeared_at', models.DateTimeField(default=None, verbose_name='исчезает')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='сила')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entities', to='pokemon_entities.pokemon', verbose_name='вид покемона')),
            ],
        ),
    ]
